### PR TITLE
new learner abess_learner in classification and regression

### PR DESCRIPTION
**Pull request by rlwanggg**
**Select template and delete others as applicable.**

# New Learner

This pull request adds **Learner[Type][Name]** with the unique key **[type].[key]** from package **{[package]}**.

I have...

* [ x ] Created a learner with the create_learner template or created one manually and it follows the identical layout.
* [ x ] Added `.train` and `.predict` private methods
* [ x ] Added `ParamSet` and if applicable `param_vals`
* [ x ] Changed learner parameter defaults and clearly documented the reason for this - !!!Delete if not applicable!!!
* [ ] Added `importance` public method and completed the documentation for this - !!!Delete if not applicable!!!
* [ ] Added `oob_error` public method and completed the documentation for this - !!!Delete if not applicable!!!
* [ x ] Added references and not left the tag blank - !!!Delete if not applicable!!!
* [ ] Removed all 'FIXME's

## Dependencies

I have...

* [ ] Added more than one dependency to suggests - If ticked, explain why below.
* [ ] Added no dependencies to imports.
* [ ] Added dependencies to remotes - If ticked, explain why below.

## Tests

I have...

* [x] Created a testthat file and it passes locally.
* [ x ] Created a paramtest file with tests for all calls in both my `.train` and `.predict` methods and it passes locally.

## Cleaning

I have run...

* [x  ] `devtools::document(roclets = c('rd', 'collate', 'namespace'))`
* [ x ] `lintr::lint_package()`

And 

* [ ] Updated NEWS.md

## Maintenance and Contributions

This PR will only be merged if the following is filled in and ticked:

* [ ] <github_name> agrees to maintain this learner going forward and agrees that this learner will be removed from `mlr3extralearners` if: i) the build remains broken for more than one month with no effort to fix it; or ii) is broken for more than three months.

The maintainer of the learner can be changed at any time by editing the '@author' tag and creating a pull request.

Finally make sure you get credit and add yourself to the DESCRIPTION file (optionally add a note to say which learner(s) you implemented):

* [ x ] I have added myself (and anyone else who contributed) to the end of the "Authors" field in the DESCRIPTION file with role "ctb" 

## Comments

-------

# Updated Learner

This pull request updates Learner[Type][Name].

## Dependencies

I have...

* [ ] Added more than one dependency to suggests - If ticked, explain why below.
* [ ] Added no dependencies to imports.
* [ ] Added dependencies to remotes - If ticked, explain why below.

## Tests

* [ ] Learner autotest is passing locally.
* [ x ] Paramtest is passing locally.
* [ ] I have run `rcmdcheck::rcmdcheck` and there are no new NOTEs, WARNINGs, or ERRORs.

## Cleaning

I have run...

* [x ] `devtools::document(roclets = c('rd', 'collate', 'namespace'))`

If you've also made changes other than a small patch (i.e. changes that could affect code style) then please also confirm:

I have run...

* [x ] `styler::style_pkg(style = styler::mlr_style)` - If needed install with `remotes::install_github('pat-s/styler@mlr-style')`
* [x ] `lintr::lint_package()`

And 

* [ ] Updated NEWS.md
* [x ] Updated the package version (For patches (bug fixing, small added feature): add 1 to the 3rd number. For minor updates (new learner, new features): add 1 to the 2nd number). 

## Comments

----

# Other

### CODE REVIEW

**Comment by sebffischer** [comment]
I will look into your failing tests tomorrow in detail

**Comment by sebffischer** [comment]
Running `devtools::check()` on your fork throws an error that 
revealed problems with your roxygen documentation of the abess learners. 

Maybe try the following minimal documentation: 

```
#' @title Regression Adaptive Best-subset Selection Learner
#' @author @rlwanggg
#' @name mlr_learners_regr.abess
#'
#' @template class_learner
#' @templateVar id regr.abess
#' @templateVar caller abess
#'
#'
#' @template seealso_learner
#' @template example
#'
#' @export
```
for regression and 
```
#' @title Classification Adaptive Best-subset Selection Learner
#' @author @rlwanggg
#' @name mlr_learners_classif.abess
#'
#' @template class_learner
#' @templateVar id classif.abess
#' @templateVar caller abess
#'
#' @template seealso_learner
#' @template example
#' @export
```
and we can see whether this solves (part of) the issue. 

Moreover you need to include the autotests for both learners in `./tests/testthat`. 

Also it might make sense for you to pull the changes from the main mlr-org branch to your fork.

**Comment by rlwanggg** [comment]
> Running `devtools::check()` on your fork throws an error that revealed problems with your roxygen documentation of the abess learners.
> 
> Maybe try the following minimal documentation:
> 
> ```
> #' @title Regression Adaptive Best-subset Selection Learner
> #' @author @rlwanggg
> #' @name mlr_learners_regr.abess
> #'
> #' @template class_learner
> #' @templateVar id regr.abess
> #' @templateVar caller abess
> #'
> #'
> #' @template seealso_learner
> #' @template example
> #'
> #' @export
> ```
> 
> for regression and
> 
> ```
> #' @title Classification Adaptive Best-subset Selection Learner
> #' @author @rlwanggg
> #' @name mlr_learners_classif.abess
> #'
> #' @template class_learner
> #' @templateVar id classif.abess
> #' @templateVar caller abess
> #'
> #' @template seealso_learner
> #' @template example
> #' @export
> ```
> 
> for classification. We can then see whether this solves (part of) the issue.
> 
> Moreover you need to include the autotests for both learners in `./tests/testthat`.
> 
> Also it might make sense for you to pull the changes from the main mlr-org branch to your fork.

Thanks a bunch！I change the documentations just now. The testthat files I included yesterday, BUT the problem is still there
—— "[train()] learner 'regr.abess:response' on task 'feat_single_logical' failed: train log has errors: x should have at least two columns!"
I tried to traceback, but some source functions are not visible,  so I don't know exactly what the problem is.

**Comment by sebffischer** [comment]
For me, the tests don't pass locally. In order to test whether learners can actually deal with the indicated feature types, the autotest constructs datasets for each allowed feature type and checks whether the learner can actually deal with the feature type. These datasets have only one predictor and looking at line 408 in the [abess.R file](https://github.com/abess-team/abess/blob/master/R-package/R/abess.R) explains that this is causes problems. 
I will discuss this tomorrow and hopefully solve this issue (changing it requires a change in the autotest setup, because currently the run_autotest function is obtained from mlr3 and the GH actions workflow use the latest CRAN version, so probably as an intermedaite fix the fix for the run_autotest function has to be defined in mlr3extralearners or the development version of mlr3 has to be used for the GH actions workflow)

**Comment by sebffischer** [comment]
As an intermediate solution you can use the `exclude` argument from the [run_autotest]() function, and exclude the tasks that use only one feature. Unfortunately this is currently not well documented. 

The tasks for the autotests are constructed using the `generate_tasks()` function. This includes the "feat_single_logical".  To disable this test pass the names of the generated tasks via the `exclude` argument.

**Comment by sebffischer** [comment]
Now there are new issues that need to be addressed. Let me know if you need further help.

**Comment by sebffischer** [comment]
Are you still interested in adding the learner and do you need more support?

**Comment by rlwanggg** [comment]
> Are you still interested in adding the learner and do you need more support?

Yes, I test it in my local and found some other problems.  we are trying to fix it with our abess.R files. Thanks a million. if I have other questions later, I may need to trouble you.

**Comment by sebffischer** [comment]
If you still intend to add the abess learner, you should first pull again from main as many changes have been made. If you have any questions don't hesitate to ask :)

**Pull request closed without merging**
