### PR TITLE
Remove extra dictionary

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
I had deliberately created the extra dictionary to avoid the long function in the zzz, I don't really mind which approach and it doesn't matter if the zzz is messy but might be slightly easier to maintain if contained in each file?

**Comment by mllg** [comment]
Ok, fair enough, but can it be avoided to overload `lrn()` and `lrns()`

**Comment by RaphaelS1** [comment]
We could move the functionality that this `lrn` and `lrns` provides by moving it to mlr3? I guess it depends what we want the default behaviour to be. mlr3 method loads the object with warning, mlr3extralearners stops code and tells user to install packages.

**Comment by mb706** [comment]
You can do something like [this](https://github.com/mlr-org/mlr3pipelines/blob/6cf97e5dc1cbece4547517d5bf9220de865d15b0/R/mlr_pipeops.R#L82-L105) (only with learner instead of pipeop).

You would then call `register_learner()` after every learner, and have a `publish_registered_learners()` call in onLoad, as [here](https://github.com/mlr-org/mlr3pipelines/blob/6cf97e5dc1cbece4547517d5bf9220de865d15b0/R/zzz.R#L18).

**Comment by RaphaelS1** [comment]
This seems almost identical to what I'm doing? Except in this package it's a list instead of an environment, what's the advantage in changing?

**Comment by RaphaelS1** [comment]
@mb706 it would be good to either close this or do what you suggested. Can you explain the advantage of your method over what we currently have?

**Comment by mb706** [comment]
You're right, I hadn't paid attention. I though the reason why you overwrite `lrn()` is that you create your own dictionary, but that is not the case.

**Pull request closed without merging**
