### PR TITLE
add custom.family parameter to learner_mboost_regr_glmboost.R

### PR DESCRIPTION
**Pull request by JaGarRod**
Add custom.family parameter to the parameter set as in learner_mboost_surv_glmboost.R

# Updated Learner

This pull request updates Learner regr.glmboost

### Reason for update

It was not possible to use a custom family for the parameter family

## Dependencies

I have...

* [ ] Added more than one dependency to suggests - If ticked, explain why below.
* [x] Added no dependencies to imports.
* [ ] Added dependencies to remotes - If ticked, explain why below.

## Tests

* [x] Learner autotest is passing locally.
* [x] Paramtest is passing locally.
* [ ] I have run `rcmdcheck::rcmdcheck` and there are no new NOTEs, WARNINGs, or ERRORs.

## Cleaning

I have run...

* [x] `devtools::document(roclets = c('rd', 'collate', 'namespace'))`
* [x] `styler::style_pkg(style = styler::mlr_style)` - If needed install with `remotes::install_github('pat-s/styler@mlr-style')`
* [x] `usethis::use_tidy_description()`
* [x] `lintr::lint_package()`

And 

* [x] Updated NEWS.md

## Comments

This is my first pull request and I ran into some problems.
I am using R4 and I can't install all project dependencies (error: Error: Failed to install 'mlr3extralearners' from GitHub:
  (converted from warning) installation of package ‘/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T//Rtmp3zXhCw/file465045f97601/mlr3extralearners_0.3.0.9000.tar.gz’ had non-zero exit status). How can I recreate the environment required to run project's tests?

I could not run some of the test nor download the 'pat-s/styler@mlr-style'.

How should I update news? What version number should I use?

What is the paramtest?

# Other

### CODE REVIEW

**Comment by RaphaelS1** [comment]
> This is my first pull requests and I ran into some problems.

I'm here to help!

> I am using R4 and I can't install all project dependencies (error: Error: Failed to install 'mlr3extralearners' from GitHub:
(converted from warning) installation of package ‘/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T//Rtmp3zXhCw/file465045f97601/mlr3extralearners_0.3.0.9000.tar.gz’

By 'R4' do you mean R version 4? I can't help without more detail but I can see you've forked the repo so all you have to do is open your local clone and then run `devtools::load_all()`

> I could not run some of the test nor download the 'pat-s/styler@mlr-style'.

Did you run `remotes::install_github('pat-s/styler@mlr-style')` ?

> How should I update news? What version number should I use?

Great question, I've updated how this works now to make it easier. Just add 1 to the  patch number (the third number) in news and description and add a short comment explaining the changes, e.g. 'now allow custom families in regr.glmboost'

> What is the paramtest?

https://github.com/mlr-org/mlr3extralearners/blob/main/inst/paramtest/test_paramtest_mboost_regr_glmboost.R

**Comment by JaGarRod** [comment]
> By 'R4' do you mean R version 4? I can't help without more detail but I can see you've forked the repo so all you have to do is open your local clone and then run devtools::load_all()

Yes, sorry, I was not very specific, I was using R 4.0.3 in Mac Os, but I ran into a lot problems (probably because of a proxy).

In a fresh installation in Windows with just R (4.0.3) and devtools installed, load_all failed because I was missing dependencies.
I did devtools::install(<path_to_ml3extralearners_repo>, dependencies=TRUE) and all dependencies were installed except for CoxBoost which was not available (it seems CoxBoost is no longer in CRAN).
I believed R tried to install catboost from source, but for that you need Rtools in Windows.
I installed Rtools for Windows.
I ran devtools::install(<path_to_ml3extralearners_repo>, dependencies=TRUE) again, this time it worked. And I was able to run devtools::load_all()
To run rcmdcheck::rcmdcheck() I first needed to install.packages("rcmdcheck").

I believe this kind of instructions would be useful to create a fresh environment in which to develop for this project.
If you give some guidance on where I can add them (these ones would be for Windows) I would be happy to upload them (or you could just use this info, of course, and put it where you consider appropriate).


I updated the pullrequest info with the fields I was able to run this time.

-  I could not run rcmdcheck::rcmdcheck() because CoxBoost package is missing from CRAN (installing an archived version failed too)
-  styler::style_pkg(style = styler::mlr_style) changed a lot of files and threw the an error. This was the report:

Status  Count   Legend
v       109     File unchanged.
i       66      File changed.
x       1       Styling threw an error.

Please review the changes carefully!
Warning message:
When processing R/create_learner.R: <text>:7:2: unexpected symbol
6:  package = "stats"
7:  caller
    ^

**Comment by RaphaelS1** [comment]
Okay so firstly you really shouldn't need to install coxboost or catboost as you are only updating mboost. I will change the instructions to remove running `rcmdcheck` as you're right this is confusing and leads to problems.

When making small updates like this you can also avoid running styler by just using the indenting built into whatever software you use (RStudio does this automatically or with cmd-I).

**Comment by RaphaelS1** [comment]
I've cleaned up the mess styler created (my fault) and will update instructions in the book and PR, sorry about that this is still a relatively new process

**Review by RaphaelS1 — APPROVED** [review]

**Pull request merged**
