### PR TITLE
fix survival model learners

### PR DESCRIPTION
**Pull request by RaphaelS1**
Leaving in drafts whilst it requires remotes, will see if checks pass

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@sebffischer where is that code from?

**Comment by sebffischer** [comment]
from mlr3proba (the sanity test)

**Comment by RaphaelS1** [comment]
Gr, thanks for spotting. Completely forgot about that

**Comment by RaphaelS1** [comment]
Should be fixed in https://github.com/mlr-org/mlr3proba/pull/252

**Pull request merged**
