### PR TITLE
fix bugs in all {survivalmodels} learners

### PR DESCRIPTION
**Pull request by RaphaelS1**
Fixes bug in all survivalmodels learners

### CODE REVIEW

**Comment by RaphaelS1** [comment]
The paramtest error is weird, have you seen it before @sebffischer ?

**Comment by sebffischer** [comment]
This is because the auto paramtest was updated I assume? (I am on my phone right now so can't check) 
There is a branch where I am fixing all the parameter tests but there are still some missing

**Comment by sebffischer** [comment]
Almost all are essentially failing since the last CRAN update of mlr3 but the tests are not triggered with the current CI, once I am done and merge the branch they will be ran daily to check for changes in the upstream packages

**Comment by sebffischer** [comment]
but why are the learner tests failing?

**Comment by sebffischer** [comment]
Please open again if needed.

**Comment by sebffischer** [comment]
I merged the latest changes into this PR. The tests are still failing

**Pull request closed without merging**
