### PR TITLE
Implement linear mixed effects models from lme4

### LINKED ISSUE #197: [LRNRQ] Add lmer from package lme4
### Algorithm

Linear mixed effects (random intercepts *and* random slopes)

### Package

`lme4`

### Supported types

* [ ] classif
* [ ] clust 
* [ ] dens
* [X] regr
* [ ] surv

### I have checked that this is not already implemented in

  * [X] mlr3
  * [X] mlr3learners
  * [X] mlr3extralearners
  * [X] Other core packages (e.g. mlr3proba, mlr3keras)

### Why do I think this is a useful learner?

Linear mixed effects modeling is useful to see how regression slopes vary among groups in a dataset (as in e.g. this paper: https://doi.org/10.1080/IW-6.3.957). In this way, one can determine how interaction terms change according to a covariate not included in the original regression.

### Further Optional Comments

Linear mixed effects modeling is already partially implemented in `mlr3pipelines` via `PipeOpEncodeLmer`. However, this only allows random intercepts. For example, with a response variable `y`, predictors `x1 x2`, and a grouping factor `g`, the pipe operator lets you make a model like `y ~ x1 + x2 + (1 | g)`. However, lme4 supports making models of the form `y ~ (1 + x1 + x2 | g)`. To my knowledge, this is not currently possible in `mlr3` and I think it would be useful to add.

### PR DESCRIPTION
**Pull request by s-kganz**
# New Learner

This pull request adds **LearnerRegrLmer** with the unique key **regr.lmer** from package **{[lme4]}**.

I have...

* [X] Created a learner with the create_learner template or created one manually and it follows the identical layout.
* [X] Added `.train` and `.predict` private methods
* [X] Added `ParamSet` and if applicable `param_vals`
* [X] Removed all 'FIXME's

## Dependencies

I have...

* [ ] Added more than one dependency to suggests - If ticked, explain why below.
* [ ] Added no dependencies to imports.
* [ ] Added dependencies to remotes - If ticked, explain why below.

## Tests

I have...

* [X] Created a testthat file and it passes locally.
* [X] Created a paramtest file with tests for all calls in both my `.train` and `.predict` methods and it passes locally.

## Cleaning

I have run...

* [X] `devtools::document(roclets = c('rd', 'collate', 'namespace'))`
* [X] `lintr::lint_package()`

And

* [X] Updated NEWS.md

## Maintenance and Contributions

This PR will only be merged if the following is filled in and ticked:

* [X] @s-kganz agrees to maintain this learner going forward and agrees that this learner will be removed from `mlr3extralearners` if: i) the build remains broken for more than one month with no effort to fix it; or ii) is broken for more than three months.

The maintainer of the learner can be changed at any time by editing the '@author' tag and creating a pull request.

Finally make sure you get credit and add yourself to the DESCRIPTION file (optionally add a note to say which learner(s) you implemented):

* [X] I have added myself (and anyone else who contributed) to the end of the "Authors" field in the DESCRIPTION file with role "ctb"

## Comments

Closes #197 . Since this learner all but requires a unique formula for each task it is run on, autotests are run one at a time.

### CODE REVIEW

**Comment by s-kganz** [comment]
Hmm, not sure what's going on with those two errors. RCMD Check passes, but 403's when it tries to commit to the repository. The learner/parameter test fails because it's not finding the lme4 package. I'm not sure why, lme4 is in the Suggests field in the description file.

**Comment by sebffischer** [comment]
Hey, thanks a lot already! :) 

the learner / parameter test is not needed anymore. (I still have to change some instructions, sorry for that). 
your test is included in the RCMD check, so looks great!

I think the commit error is also not problematic and will resolve itself when we merge

**Comment by sebffischer** [comment]
some explanations: the "default" in the parameters is currently only used in the documentation. We want the learner to be initialiable without having lme4 loaded, therefore I put the `lme4::xxx` calls in the default params in quotes. 
Also I included some minor changes that were not related to your PR to be able to create the documentation.

**Comment by s-kganz** [comment]
@sebffischer , thanks for the clean-up, glad I was able to be helpful :). I have no changes to request, if all is good on your end I think it can be merged.

**Pull request merged**
